---
title: "Contacto"
lang: es
toc: true
toc-depth: 3
---

## Información de contacto

**Correo electrónico:** kangminku.kr@gmail.com

**Redes sociales:**

- LinkedIn: <https://www.linkedin.com/in/kangminku/>
- Facebook: <https://facebook.com/kaangminku>
- Instagram: <https://instagram.com/kangminku.kr/>

📍 Seúl, Corea

¡Hola! Estoy abierto a colaborar en los temas que me interesan. No dudes en escribirme en cualquier momento a kangminku.kr@gmail.com, y te responderé en un plazo de 24 horas. Si no tienes noticias mías, un mensaje a mi teléfono siempre será bienvenido.

## Áreas de interés

Determinantes sociales de la salud, salud en el trabajo, salud comunitaria, sistemas y políticas de salud, salud mental pública, epidemiología social, desigualdades en salud, prevención del suicidio, medicina del trabajo, política social, medicina preventiva, medicina del estilo de vida, recursos humanos en salud, urbanismo y salud, ciudades saludables, preparación ante pandemias, salud ambiental, salud global, políticas públicas, Estado de bienestar, sociología política, institucionalismo de la elección racional, investigación macrocomparativa y derechos humanos.
